function sigmaL = sigmaL(x)
%SIGMAL
%    SIGMAL = SIGMAL(X1,X2,X3,X4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Mar-2018 17:28:35
x1 = x(1);
x2 = x(2);
x3 = x(3);
x4 = x(4);

t2 = x1.^2;
t3 = x2.^2;
t4 = x3.^2;
t5 = x4.^2;
sigmaL = [t2.^2,t2.*x1.*x2,t2.*x1.*x3,t2.*x1.*x4,t2.*t3,t2.*x2.*x3,t2.*x2.*x4,t2.*t4,t2.*x3.*x4,t2.*t5,t2,t3.*x1.*x2,t3.*x1.*x3,t3.*x1.*x4,t4.*x1.*x2,x1.*x2.*x3.*x4,t5.*x1.*x2,x1.*x2,t4.*x1.*x3,t4.*x1.*x4,t5.*x1.*x3,x1.*x3,t5.*x1.*x4,x1.*x4,t3.^2,t3.*x2.*x3,t3.*x2.*x4,t3.*t4,t3.*x3.*x4,t3.*t5,t3,t4.*x2.*x3,t4.*x2.*x4,t5.*x2.*x3,x2.*x3,t5.*x2.*x4,x2.*x4,t4.^2,t4.*x3.*x4,t4.*t5,t4,t5.*x3.*x4,x3.*x4,t5.^2,t5];
